---
- file:
    state=directory
    path={{ item }}
    owner=www-data
    group=www-data
  with_items:
    - /var/apps/slides
    - /var/apps/slides/code
    - /var/apps/slides/logs
    - /var/apps/slides/nginx

- git:
    repo=https://github.com/grekko/reveal.js.git
    dest=/var/apps/slides/code
    update=yes
    version=htw-bootloader

- npm:
    path=/var/apps/slides/code

- copy:
    src=slides.service
    dest=/var/apps/slides/slides.service
    mode=0755

- file:
    state=link
    src=/var/apps/slides/slides.service
    dest=/etc/systemd/system/slides.service
  register: slides_service

- file:
    state=directory
    path=/var/apps/slides/code
    owner=www-data
    group=www-data
    recurse=yes

- shell: >
    systemctl start slides
  when: slides_service.changed

- copy:
    src=nginx/vhost-proxy.conf
    dest=/var/apps/slides/nginx/vhost-proxy.conf

- file:
    state=link
    src=/var/apps/slides/nginx/vhost-proxy.conf
    dest=/etc/nginx/sites-enabled/slides.conf
  notify: reload nginx

