---
- file:
    state=directory
    path={{ item }}
    owner={{ ansible_ssh_user }}
    group={{ ansible_ssh_user }}
  with_items:
    - /var/apps/portal/public
    - /var/apps/portal/logs
    - /var/apps/portal/nginx

- template:
    src=nginx/portal-vhost.conf.j2
    dest=/var/apps/portal/nginx/vhost.conf
    owner={{ ansible_ssh_user }}
    group={{ ansible_ssh_user }}
  notify: reload nginx

- file:
    state=link
    src=/var/apps/portal/nginx/vhost.conf
    dest=/etc/nginx/sites-enabled/portal.conf
  notify: reload nginx
