---
- name: Creates ssh-clients group for ssh access
  group:
    name=ssh-clients
    state=present

# WARNING: This needs to happen before we enable ssh-clients only ssh access!
- name: Add current remote_user to the ssh-clients group
  user:
    name="{{ ansible_ssh_user }}"
    append=yes
    groups=ssh-clients

- name: Ensure there is no AllowUser declarative
  lineinfile:
    backup=yes
    state=absent
    dest=/etc/ssh/sshd_config
    regexp='AllowUsers .*'
  notify: restart sshd

- name: Ensure the AllowGroups declarative exists
  lineinfile:
    dest=/etc/ssh/sshd_config
    line='AllowGroups ssh-clients'
  notify: restart sshd

