---
# TODO: Just exec when the package is not yet intalled. Detect the installation?
- name: Import passenger repository
  shell: 'sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7'

- name: Adds HTTPs support for APT
  apt:
    name={{ item }}
    state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Adds APT repo
  shell: "sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main' > /etc/apt/sources.list.d/passenger.list"
