---
- name: Create passenger-config
  shell: passenger-config --root
  register: registered_passenger_config_path

- name: Write nginx config files (depends on passenger-config)
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    mode=0644
  notify: restart nginx

- name: Create nginx sites-enabled folder
  file:
    path=/etc/nginx/sites-enabled
    state=directory
    owner=root
    group=root
    mode=0755

- name: Remove system default server
  file:
    state=absent
    path=/etc/nginx/conf.d/default.conf

# FIXME: Not sure if this even works :-/
# Symlink seems to persist after deleting it.
# Though the actual file seems to be deleted in sites-available
- name: Ensure the default site is not enabled
  file:
    state=absent
    path=/etc/nginx/sites-available/default
  notify: restart nginx
