---
# Prep user permissions, ssh access
# Create user without login!!
# - shell: sudo adduser myappuser
# - shell: mkdir -p ~myappuser/.ssh
# - shell: sh -c "cat $HOME/.ssh/authorized_keys >> ~myappuser/.ssh/authorized_keys"
# - shell: chown -R myappuser: ~myappuser/.ssh
# - shell: chmod 700 ~myappuser/.ssh
# - shell: sh -c "chmod 600 ~myappuser/.ssh/*"

# Prep app setup
# - shell: mkdir -p /var/www/myapp
# - shell: "chown myappuser: /var/www/myapp"
# - shell: "sudo -u myappuser -H git clone git://github.com/grekko/bettercooking.git /var/www/myapp/code"

# This has to run after each git push -> git hook
# - shell: "bundle install --deployment --without development test"
# - shell: "bundle exec rake assets:precompile db:migrate"
# - shell: "passenger-config restart-app $(pwd)"

# Secrets are provided by my service which writes to an ENV file ?

# Setup virtual host in nginx
# See vhost.conf.sample

