---
- name: Creates rubies directory /opt/rubies
  file:
    path=/opt/rubies state=directory

- name: Downloads configured ruby version {{ chruby_ruby_install_version }}
  get_url:
    url=https://github.com/postmodern/ruby-install/archive/v{{ chruby_ruby_install_version }}.tar.gz
    dest=/opt/build/ruby-install-{{ chruby_ruby_install_version }}.tar.gz
    sha256sum={{ chruby_ruby_install_checksum }}

- name: Unwraps downloaded ruby archive
  unarchive:
    src=/opt/build/ruby-install-{{ chruby_ruby_install_version }}.tar.gz
    dest=/opt/build/
    copy=no
  register: ruby_install_unarchive

- name: Runs make for chruby if it has just been unwrapped
  shell: make -j {{ 1 + (ansible_processor_vcpus | int) }} install chdir=/opt/build/ruby-install-{{ chruby_ruby_install_version }}
  when: ruby_install_unarchive.changed
