---
- name: Create nginx vhost for jenkins
  copy:
    src=nginx/vhost.conf
    dest=/var/lib/jenkins/nginx-vhost.conf

- name: Enable jenkins vhost config
  file:
    state=link
    src=/var/lib/jenkins/nginx-vhost.conf
    dest=/etc/nginx/sites-enabled/jenkins.conf
  notify: reload nginx

