---
- set_fact:
    jenkins_file_path: /opt/aris/config/jenkins_jobs.yml
    jenkins_processing_file_path: /opt/aris/config/jenkins_jobs.processing.yml

- include: 00-fail-when-running.yml
- include: 00-prepare-processing-file.yml
- include: 10-create-jenkins-jobs.yml
- include: 99-archive-processing-file.yml

