---
- name: Install postgresql
  apt:
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - postgresql-9.4
    - postgresql-server-dev-9.4
    - postgresql-client-9.4

- name: Install python module for ansible postgres commands (depends on postgres headers)
  easy_install:
    name=psycopg2

- name: Copy authentication configuration file to /etc/postgresql/9.4/main/pg_hba.conf
  copy:
    src=postgres/pg_hba.conf
    dest=/etc/postgresql/9.4/main/pg_hba.conf
    owner=postgres
    group=postgres
    mode=u=rw,g=r,o=r
  notify: restart postgresql
