---
- name: Ensure aris app (and config) directory exists
  file:
    path={{ item }}
    state=directory
    owner=aris
    group=aris
    mode=u=rwx,g=rwx,o=r
  with_items:
    - /opt/aris/config
    - /opt/aris/config/archive
    - /opt/aris/code
    - /opt/aris/logs

- name: Checkout the aris ansible repo
  git:
    accept_hostkey=true
    repo=https://github.com/HTW-Webtech/ai-webtech-ansible.git
    dest=/opt/aris/code/ansible
    update=yes
    version=HEAD
    force=yes

- name: Fix permissions for git repo
  file:
    path=/opt/aris/code/ansible
    owner=aris
    group=aris
    recurse=yes
