#!/bin/bash
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
source /home/{{ item.key }}/.bashrc.ruby-version

# FIXME: Currenyly every user needs to install bundler (which is kind of stupid)
# Also everybody needs to install rails etc. If I can install it via root it
# will be available to every user instead.
which bundle || gem install bundler
bundle install --deployment --without development test
bundle exec rake assets:precompile db:migrate

# Replace the apps-public folder with a symlink to the code/public
if [ -e /var/apps/{{ item.key }}/code/public ]; then
  echo "Public dir in .git repo detected. Using it in place of the default public dir"
  rm /var/apps/{{ item.key }}/public
  ln -s /var/apps/{{ item.key }}/code/public /var/apps/{{ item.key }}/public
else
  echo "No Public dir in .git repo found. Using the default public dir."
  rm /var/apps/{{ item.key }}/public
  ln -s /var/apps/{{ item.key }}/default-public /var/apps/{{ item.key }}/public
fi

# Symlink code/log/production.log if it exists
ln -s /var/apps/{{ item.key }}/code/log/production.log /var/apps/{{ item.key }}/logs/rails.log

passenger-config restart-app /var/apps/{{ item.key }}/code
