---
- name: Install ansible and postgresql
  apt:
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - software-properties-common
    - ansible
    - python-pip
    - python-dev
    - postgresql-9.4
    - postgresql-server-dev-9.4
    - postgresql-client-9.4

- name: Install psycopg2 for postgresl modules
  easy_install:
    name=psycopg2

# - name: Set a secret password for postgres user
#   postgresql_user:
#     login_user=postgres
#     login_password=
- name: Ensure aris user exists
  user:
    name=aris
    createhome=yes
    shell=/bin/bash
    state=present

- name: Ensure aris app (and config) directory exists
  file:
    path={{ item }}
    state=directory
    owner=aris
    mode=u=rw,g=rw,o=r
  with_items:
    - /opt/aris/config
    - /opt/aris/code
    - /opt/aris/logs

# FIXME: This is only for testing purposes
- name: Copies dummy Usersfile to aris
  copy:
    src=Usersfile
    dest=/opt/aris/config/Usersfile

- name: Copies private key for git access to server
  copy:
    src=key
    dest=/opt/aris/config/key
    mode=u=r,g=,o=

- name: Checkout the aris ansible repo
  git:
    key_file=/opt/aris/config/key
    accept_hostkey=true
    repo=git@github.com:grekko/htw.aris-secret.git
    dest=/opt/aris/code/ansible
    update=yes
    version=HEAD

- name: Ensure aris ansible repo has the correct owner
  file:
    path=/opt/aris/code/ansible
    owner=aris
    mode=u=rw,g=rw,o=r

- name: Setup crontab for aris user-management background service
  cron:
    minute=*/2
    job=
    user=aris
    state=present
# Consider Logging, non-verbose
# Run each 5 minutes the Setup task
# - Improvement idea: Run each minute.. check that the Usersfile has been edited since last run
# - Keept .last-run file
