---
- name: Install ansible dependencies
  apt:
    name={{ item }}
    state=present
    update_cache=true
  with_items:
    - software-properties-common
    - python-pip
    - python-dev

- name: Ensure directory for ansible exists
  file:
    path=/opt/ansible
    state=directory

- name: Checkout ansible from git repo
  git:
    repo=git://github.com/ansible/ansible.git
    recursive=yes
    dest=/opt/ansible/code
    version=v1.9.2-0.2.rc2
    accept_hostkey=yes
    force=yes

- name: Install dependant python modules
  easy_install:
    name={{ item}}
  with_items:
  - paramiko
  - PyYAML
  - Jinja2
  - httplib2
  - six
