---
# FIXME: What a crazy effort to create the aris user and database!
- name: Add postgres user to ssh-clients group for ssh access
  user:
    name=postgres
    groups=ssh-clients
    append=yes

- name: Create .ssh dir for postgres user
  file:
    path=~postgres/.ssh
    state=directory
    owner=postgres
    group=postgres
    mode=u=rwx,g=rx,o=

- name: Enable ssh access to postgres user via public ssh key
  template:
    src=ssh/postgres-user.authorized_keys.j2
    dest=~postgres/.ssh/authorized_keys
    owner=postgres
    group=postgres
    mode=u=rw,g=r,o=

- name: Ensure aris database exists
  remote_user: postgres
  sudo: no
  postgresql_db:
    name=aris

# FIXME: on Production this uses user `local` instead of `posgres`
- name: Ensure aris user has access to aris database
  remote_user: postgres
  sudo: no
  postgresql_user:
    db=aris
    name={{ lookup('env','ARIS_POSTGRES_LOGIN') }}
    password={{ lookup('env','ARIS_POSTGRES_PASSWORD') }}
    priv=ALL
    role_attr_flags=SUPERUSER

