---
- name: Fetch aris-web-ui configuration from env
  set_fact:
    app_admin_password: "{{ lookup('env','APP_ADMIN_PASSWORD') }}"
    app_secret_key_base: "{{ lookup('env','APP_SECRET_KEY_BASE') }}"
    app_pg_database: "{{ lookup('env','APP_POSTGRES_DATABASE') }}"
    app_pg_login: "{{ lookup('env','APP_POSTGRES_LOGIN') }}"
    app_pg_password: "{{ lookup('env','APP_POSTGRES_PASSWORD') }}"
    app_git_ssh_public_host: "{{ lookup('env','APP_GIT_SSH_PUBLIC_HOST') }}"

- name: Create admin os user account (with full shell access)
  user:
    name=admin
    createhome=yes
    shell=/bin/bash
    append=yes
    groups=ssh-clients,aris
    state=present

- name: Install aris-control gem
  gem:
    name=aris-control
    state=latest
    user_install=no
    executable=/opt/rubies/{{ chruby_ruby_version }}/bin/gem

- template:
    src=aris/nginx/default_env_vars.conf.j2
    dest=/var/apps/admin/nginx/extras/default_env_vars.conf
    owner=admin
    group=admin

- template:
    src=aris/rails/.env.j2
    dest=/var/apps/admin/code/.env
    owner=admin
    group=admin

