---
- name: Create users app dir (git-repo)
  file:
    state=directory
    path=/var/apps/{{ item.key }}/code
  with_dict: "{{ aris_users }}"

- name: Create symlink for uses public-dir (expects code/public to exists)
  file:
    state=link
    src=/var/apps/{{ item.key }}/code/public
    dest=/var/apps/{{ item.key }}/public
  with_dict: "{{ aris_users }}"

- name: Create users app logs dir
  file:
    state=directory
    force=yes
    path=/var/apps/{{ item.key }}/logs
  with_dict: "{{ aris_users }}"

- name: Initialize empty git repository with basic config if not existant
  shell: cd /var/apps/{{ item.key}}/code; stat .git || git init && git config receive.denyCurrentBranch ignore
  with_dict: "{{ aris_users }}"

- name: Configure proper git post-update hook
  template:
    src=git-hooks/post-update
    dest=/var/apps/{{ item.key }}/code/.git/hooks/post-update
    owner={{ item.key }}
    group={{ item.key }}
  with_dict: "{{ aris_users }}"

- name: Configure proper git post-receive hook (which runs `git reset --hard after` after push)
  template:
    src=git-hooks/post-receive
    dest=/var/apps/{{ item.key }}/code/.git/hooks/post-receive
    owner={{ item.key }}
    group={{ item.key }}
  with_dict: "{{ aris_users }}"

- name: Create or update .env file in app-directory
  template:
    src=user-app/.env
    dest=/var/apps/{{ item.key }}/code/.env
    owner={{ item.key }}
    group={{ item.key }}
  with_dict: "{{ aris_users }}"

# FIXME: DANGER! This loads env vars into the user account!! is that a problem? Remote code exec?
- name: Ensure the .env file is loaded in users ~/.bashrc to enable access to ENV vars for rake etc.
  lineinfile:
    line='source /var/apps/{{ item.key }}/code/.env'
    dest="~{{ item.key }}/.bashrc"
  with_dict: "{{ aris_users }}"

# FIXME: seems like a pretty harsh thing to do
- name: Ensure the correct ownership and permissions for the users app dir
  file:
    state=directory
    path=/var/apps/{{ item.key }}
    recurse=yes
    owner={{ item.key }}
    group={{ item.key }}
    mode=ug+rwx
  with_dict: "{{ aris_users }}"
