---
- name: Create or update .env file in app-directory
  template:
    src=user-app/.env
    dest=/var/apps/{{ item.key }}/code/.env
    owner={{ item.key }}
    group={{ item.key }}
  with_dict: "{{ aris_apps }}"

- name: Ensure the .env file is loaded in users ~/.bashrc to enable access to ENV vars for rake etc.
  lineinfile:
    line='source /var/apps/{{ item.key }}/code/.env'
    dest="~{{ item.key }}/.bashrc"
  with_dict: "{{ aris_apps }}"

